//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BkSevadhariWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CenterMaster()
        {
            this.SevaDhariMasters = new HashSet<SevaDhariMaster>();
        }
    
        public int CertificateNo { get; set; }
        public string CenterName { get; set; }
        public string TeacherName { get; set; }
        public string InChargeName { get; set; }
        public string PadNo { get; set; }
        public string Zone { get; set; }
        public string SubZone { get; set; }
        public string MobileNo { get; set; }
        public string MobileNo1 { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string PinNo { get; set; }
        public System.DateTime CreatedModifiedOn { get; set; }
        public int IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SevaDhariMaster> SevaDhariMasters { get; set; }
    }
}
