//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BkSevadhariWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MadhubanLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MadhubanLocation()
        {
            this.SevadhariDetails = new HashSet<SevadhariDetail>();
        }
    
        public int MadhubanLocId { get; set; }
        public string Name { get; set; }
        public int IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SevadhariDetail> SevadhariDetails { get; set; }
    }
}
