//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BkSevadhariWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SevaDhariMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SevaDhariMaster()
        {
            this.SevadhariDetails = new HashSet<SevadhariDetail>();
        }
    
        public int SmId { get; set; }
        public string RegistrationNo { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string MobileNo { get; set; }
        public string MobileNo1 { get; set; }
        public string Email { get; set; }
        public string Occupation { get; set; }
        public string Address { get; set; }
        public Nullable<byte> YearsInGyan { get; set; }
        public Nullable<int> ProofTypeId { get; set; }
        public string IdProofNumber { get; set; }
        public string ImagePath { get; set; }
        public System.DateTime CreatedModifiedOn { get; set; }
        public string BlackList { get; set; }
        public string Qualification { get; set; }
        public string HealthInfo { get; set; }
        public string Note { get; set; }
        public string MadhubanCode { get; set; }
        public Nullable<int> CertificateNo { get; set; }
        public int IsDeleted { get; set; }
    
        public virtual CenterMaster CenterMaster { get; set; }
        public virtual IdProofType IdProofType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SevadhariDetail> SevadhariDetails { get; set; }
    }
}
